In [ ]:
# Step 1: Data exploration

In [3]:
import pandas as pd
import numpy as np
import pyarrow.parquet as pq


files = [
    'Benign-Monday-no-metadata.parquet',
    'Botnet-Friday-no-metadata.parquet',
    'Bruteforce-Tuesday-no-metadata.parquet',
    'DDoS-Friday-no-metadata.parquet',
    'DoS-Wednesday-no-metadata.parquet',
    'Infiltration-Thursday-no-metadata.parquet',
    'Portscan-Friday-no-metadata.parquet'
]

df = pd.concat([pd.read_parquet(file) for file in files])

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df.head()

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Packet Length Min,Packet Length Max,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Avg Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init Fwd Win Bytes,Init Bwd Win Bytes,Fwd Act Data Packets,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,6,4,2,0,12,0,6,6,6.00000,0.000000,0,0,0.0,0.000000,3.000000e+06,5.000000e+05,4.000000,0.000000,4,4,4,4.0,0.000000,4,4,0,0.000000,0.000000,0,0,0,0,0,0,40,0,5.000000e+05,0.000000,6,6,6.000000,0.000000,0.000000,0,0,0,0,1,1,0,0,0,9.00000,6.00000,0.0,0,0,0,0,0,0,2,12,0,0,329,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1,6,1,2,0,12,0,6,6,6.00000,0.000000,0,0,0.0,0.000000,1.200000e+07,2.000000e+06,1.000000,0.000000,1,1,1,1.0,0.000000,1,1,0,0.000000,0.000000,0,0,0,0,0,0,40,0,2.000000e+06,0.000000,6,6,6.000000,0.000000,0.000000,0,0,0,0,1,1,0,0,0,9.00000,6.00000,0.0,0,0,0,0,0,0,2,12,0,0,329,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
2,6,3,2,0,12,0,6,6,6.00000,0.000000,0,0,0.0,0.000000,4.000000e+06,6.666667e+05,3.000000,0.000000,3,3,3,3.0,0.000000,3,3,0,0.000000,0.000000,0,0,0,0,0,0,40,0,6.666667e+05,0.000000,6,6,6.000000,0.000000,0.000000,0,0,0,0,1,1,0,0,0,9.00000,6.00000,0.0,0,0,0,0,0,0,2,12,0,0,245,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
3,6,1,2,0,12,0,6,6,6.00000,0.000000,0,0,0.0,0.000000,1.200000e+07,2.000000e+06,1.000000,0.000000,1,1,1,1.0,0.000000,1,1,0,0.000000,0.000000,0,0,0,0,0,0,40,0,2.000000e+06,0.000000,6,6,6.000000,0.000000,0.000000,0,0,0,0,1,1,0,0,0,9.00000,6.00000,0.0,0,0,0,0,0,0,2,12,0,0,245,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
4,6,609,7,4,484,414,233,0,69.14286,111.967896,207,0,103.5,119.511505,1.474548e+06,1.806240e+04,60.900002,115.194954,381,2,609,101.5,177.089523,460,2,467,155.666672,263.560883,460,3,0,0,0,0,164,104,1.149425e+04,6568.144531,0,233,74.833336,107.527443,11562.151367,0,0,0,1,0,0,0,0,0,81.63636,69.14286,103.5,0,0,0,0,0,0,7,484,4,414,8192,2053,5,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2157990 entries, 0 to 119521
Data columns (total 78 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Protocol                  int8
 1   Flow Duration             int32
 2   Total Fwd Packets         int32
 3   Total Backward Packets    int32
 4   Fwd Packets Length Total  int32
 5   Bwd Packets Length Total  int32
 6   Fwd Packet Length Max     int16
 7   Fwd Packet Length Min     int16
 8   Fwd Packet Length Mean    float32
 9   Fwd Packet Length Std     float32
 10  Bwd Packet Length Max     int16
 11  Bwd Packet Length Min     int16
 12  Bwd Packet Length Mean    float32
 13  Bwd Packet Length Std     float32
 14  Flow Bytes/s              float64
 15  Flow Packets/s            float64
 16  Flow IAT Mean             float32
 17  Flow IAT Std              float32
 18  Flow IAT Max              int32
 19  Flow IAT Min              int32
 20  Fwd IAT Total             int32
 21  Fwd IAT Mean              float32
 22  Fwd IAT Std               float32
 23  Fwd IAT Max               int32
 24  Fwd IAT Min               int32
 25  Bwd IAT Total             int32
 26  Bwd IAT Mean              float32
 27  Bwd IAT Std               float32
 28  Bwd IAT Max               int32
 29  Bwd IAT Min               int32
 30  Fwd PSH Flags             int8
 31  Bwd PSH Flags             int8
 32  Fwd URG Flags             int8
 33  Bwd URG Flags             int8
 34  Fwd Header Length         int64
 35  Bwd Header Length         int32
 36  Fwd Packets/s             float32
 37  Bwd Packets/s             float32
 38  Packet Length Min         int16
 39  Packet Length Max         int16
 40  Packet Length Mean        float32
 41  Packet Length Std         float32
 42  Packet Length Variance    float32
 43  FIN Flag Count            int8
 44  SYN Flag Count            int8
 45  RST Flag Count            int8
 46  PSH Flag Count            int8
 47  ACK Flag Count            int8
 48  URG Flag Count            int8
 49  CWE Flag Count            int8
 50  ECE Flag Count            int8
 51  Down/Up Ratio             int16
 52  Avg Packet Size           float32
 53  Avg Fwd Segment Size      float32
 54  Avg Bwd Segment Size      float32
 55  Fwd Avg Bytes/Bulk        int8
 56  Fwd Avg Packets/Bulk      int8
 57  Fwd Avg Bulk Rate         int8
 58  Bwd Avg Bytes/Bulk        int8
 59  Bwd Avg Packets/Bulk      int8
 60  Bwd Avg Bulk Rate         int8
 61  Subflow Fwd Packets       int32
 62  Subflow Fwd Bytes         int32
 63  Subflow Bwd Packets       int32
 64  Subflow Bwd Bytes         int32
 65  Init Fwd Win Bytes        int32
 66  Init Bwd Win Bytes        int32
 67  Fwd Act Data Packets      int32
 68  Fwd Seg Size Min          int32
 69  Active Mean               float32
 70  Active Std                float32
 71  Active Max                int32
 72  Active Min                int32
 73  Idle Mean                 float32
 74  Idle Std                  float32
 75  Idle Max                  int32
 76  Idle Min                  int32
 77  Label                     object
dtypes: float32(22), float64(2), int16(7), int32(26), int64(1), int8(19), object(1)
memory usage: 545.4+ MB

In [5]:
df.describe()

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Packet Length Min,Packet Length Max,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Avg Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init Fwd Win Bytes,Init Bwd Win Bytes,Fwd Act Data Packets,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2157990.0,2.157990e+06,2157990.0,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2157990.0,2157990.0,2157990.0,2157990.0,2157990.0,2157990.0,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2.157990e+06,2157990.0,2.157990e+06,2.157990e+06,2.157990e+06
mean,1.043039e+01,1.839954e+07,1.070301e+01,1.204134e+01,6.708976e+02,1.868441e+04,2.556723e+02,2.125437e+01,7.009832e+01,8.533633e+01,1.108346e+03,4.738000e+01,3.864349e+02,4.301746e+02,4.852093e+05,1.988978e+04,1.616580e+06,3.702820e+06,1.168965e+07,1.902131e+05,1.802444e+07,3.253552e+06,4.192625e+06,1.151616e+07,1.231523e+06,1.209015e+07,2.219984e+06,1.881383e+06,5.865129e+06,1.171025e+06,3.844364e-02,0.0,1.065807e-05,0.0,-3.413998e+04,-3.017459e+03,1.560727e+04,4.349699e+03,1.853202e+01,1.207405e+03,2.144860e+02,3.748980e+02,6.312511e+05,3.470266e-02,3.844364e-02,2.919383e-04,2.726389e-01,2.915495e-01,8.993786e-02,1.065807e-05,2.933285e-04,7.063559e-01,2.383874e+02,7.009832e+01,3.864349e+02,0.0,0.0,0.0,0.0,0.0,0.0,1.070301e+01,6.708839e+02,1.204134e+01,1.868401e+04,7.297457e+03,2.099985e+03,6.073346e+00,-3.604978e+03,1.011062e+05,5.026611e+04,1.879392e+05,7.251217e+04,10616468.0,6.505696e+05,1.110712e+07,1.010863e+07
std,5.401337e+00,3.661167e+07,7.985091e+02,1.062333e+03,1.123520e+04,2.402618e+06,8.029173e+02,6.473605e+01,2.078149e+02,3.162913e+02,2.161148e+03,7.298299e+01,6.676905e+02,9.382000e+02,8.008648e+06,1.220244e+05,4.911692e+06,8.913727e+06,2.723544e+07,3.189423e+06,3.656193e+07,1.044325e+07,1.081798e+07,2.733259e+07,9.427160e+06,3.130795e+07,9.766596e+06,7.077064e+06,1.914589e+07,9.128242e+06,1.922648e-01,0.0,3.264653e-03,0.0,2.411218e+07,1.663217e+06,1.114134e+05,3.005593e+04,2.640535e+01,2.245988e+03,3.336813e+02,7.005270e+02,1.861915e+06,1.830257e-01,1.922648e-01,1.708371e-02,4.453168e-01,4.544761e-01,2.860928e-01,3.264653e-03,1.712433e-02,7.212362e-01,3.612477e+02,2.078149e+02,6.676905e+02,0.0,0.0,0.0,0.0,0.0,0.0,7.985091e+02,1.121943e+04,1.062333e+03,2.402562e+06,1.490283e+04,8.704626e+03,6.630033e+02,1.242655e+06,7.209183e+05,4.379099e+05,1.138157e+06,6.411264e+05,26382170.0,5.240587e+06,2.719600e+07,2.611618e+07
min,0.000000e+00,-1.300000e+01,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.930000e+08,-2.000000e+06,-1.300000e+01,0.000000e+00,-1.300000e+01,-1.400000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,-3.221223e+10,-1.073741e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.000000e+00,-1.000000e+00,0.000000e+00,-5.368707e+08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
25%,6.000000e+00,5.360000e+02,2.000000e+00,1.000000e+00,3.100000e+01,2.600000e+01,2.000000e+01,0.000000e+00,8.666667e+00,0.000000e+00,6.000000e+00,0.000000e+00,6.000000e+00,0.000000e+00,1.193282e+02,1.343816e+00,3.396667e+02,1.474181e+01,5.100000e+02,3.000000e+00,2.000000e+00,2.000000e+00,0.000000e+00,2.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,4.000000e+01,3.200000e+01,8.357257e-01,1.730278e-01,0.000000e+00,4.600000e+01,2.987500e+01,8.763561e+00,7.680000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.516667e+01,8.666667e+00,6.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,2.000000e+00,3.100000e+01,1.000000e+00,2.600000e+01,-1.000000e+00,-1.000000e+00,0.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
50%,6.000000e+00,6.867650e+04,2.000000e+00,2.000000e+00,7.400000e+01,1.860000e+02,4.300000e+01,6.000000e+00,3.959091e+01,0.000000e+00,1.110000e+02,0.000000e+00,1.020000e+02,0.000000e+00,3.043949e+03,5.932942e+01,2.998700e+04,1.778240e+04,6.048900e+04,4.000000e+00,4.000000e+02,2.580000e+02,0.000000e+00,3.610000e+02,3.000000e+00,4.000000e+00,4.000000e+00,0.000000e+00,4.000000e+00,3.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,6.400000e+01,6.400000e+01,3.096782e+01,1.647474e+01,6.000000e+00,1.170000e+02,6.933334e+01,3.810512e+01,1.452000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,8.850000e+01,3.959091e+01,1.020000e+02,0.0,0.0,0.0,0.0,0.0,0.0,2.000000e+00,7.400000e+01,2.000000e+00,1.860000e+02,2.350000e+02,-1.000000e+00,1.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
75%,1.700000e+01,5.979046e+06,6.000000e+00,6.000000e+00,3.580000e+02,2.937000e+03,2.950000e+02,3.900000e+01,5.400000e+01,8.938293e+01,1.418000e+03,9.000000e+01,2.850000e+02,4.816452e+02,2.962963e+04,4.662005e+03,8.695537e+05,2.012102e+06,5.591671e+06,7.500000e+01,5.648462e+06,1.065564e+06,1.836362e+06,5.330757e+06,6.000000e+01,2.301185e+05,4.261295e+04,5.305412e+04,1.476075e+05,4.800000e+01,0.000000e+00,0.0,0.000000e+00,0.0,1.640000e+02,1.360000e+02,2.944063e+03,8.519339e+01,3.800000e+01,1.448000e+03,2.040000e+02,4.344991e+02,1.887895e+05,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,2.190000e+02,5.400000e+01,2.850000e+02,0.0,0.0,0.0,0.0,0.0,0.0,6.000000e+00,3.580000e+02,6.000000e+00,2.937000e+03,8.192000e+03,2.350000e+02,3.000000e+00,3.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
max,1.700000e+01,1.200000e+08,2.197590e+05,2.919220e+05,1.290000e+07,6.554530e+08,2.482000e+04,2.325000e+03,5.940857e+03,7.125597e+03,1.953000e+04,2.896000e+03,5.800500e+03,8.194660e+03,2.071000e+09,4.000000e+06,1.200000e+08,8.480026e+07,1.200000e+08,1.200000e+08,1.200000e+08,1.200000e+08,8.460293e+07,1.200000e+08,1.200000e+08,1.200000e+08,1.200000e+08,8.441802e+07,1.200000e+08,1.200000e+08,1.000000e+00,0.0,1.000000e+00,0.0,4.644908e+06,5.838440e+06,3.000000e+06,2.000000e+06,1.448000e+03,2.482000e+04,3.337143e+03,4.731522e+03,2.240000e+07,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.560000e+02,3.893333e+03,5.940857e+03,5.800500e+03,0.0,0.0,0.0,0.0,0.0,0.0,2.197590e+05,1.287034e+07,2.919220e+05,6.554530e+08,6.553500e+04,6.553500e+04,2.135570e+05,1.380000e+02,1.100000e+08,7.420000e+07,1.100000e+08,1.100000e+08,120000000.0,7.690000e+07,1.200000e+08,1.200000e+08

In [6]:
df.isnull().sum()

Protocol                    0
Flow Duration               0
Total Fwd Packets           0
Total Backward Packets      0
Fwd Packets Length Total    0
                           ..
Idle Mean                   0
Idle Std                    0
Idle Max                    0
Idle Min                    0
Label                       0
Length: 78, dtype: int64

In [7]:
df['Label'].unique()

array(['Benign', 'Bot', 'FTP-Patator', 'SSH-Patator', 'DDoS',
       'DoS slowloris', 'DoS Slowhttptest', 'DoS Hulk', 'DoS GoldenEye',
       'Heartbleed', 'Infiltration', 'PortScan'], dtype=object)

In [8]:
df['Label'].value_counts()

Label
Benign              1823641
DoS Hulk             172846
DDoS                 128014
DoS GoldenEye         10286
FTP-Patator            5931
DoS slowloris          5385
DoS Slowhttptest       5228
SSH-Patator            3219
PortScan               1956
Bot                    1437
Infiltration             36
Heartbleed               11
Name: count, dtype: int64

In [9]:
# SUMMARY: Now we conclude that the dataset is clean with 78 useful features and 11 attacks. However, the datasets are imbalance.

In [11]:
# Step 2: Data Processing 'since the datasets are clean we will now proceed to step 3'

In [12]:
# Step 3: Feature Selection

In [13]:
# Let's try two feature slection

In [4]:
X = df.drop('Label', axis=1)
y = df['Label']

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X, y)
tree_importances = model.feature_importances_

In [ ]:
print(tree_importances)

In [1]:
# test to commit